# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='changed_recently',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='changed_recently',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
