all: hw06.cpp Warrior.h Warrior.cpp Noble.h Noble.cpp
	g++ hw06.cpp Warrior.h Warrior.cpp Noble.h Noble.cpp -o swag

run: swag
	g++ hw06.cpp Warrior.h Warrior.cpp Noble.h Noble.cpp -o swag	
	./swag

clean: swag
	rm swag