all: hw07.cpp polynomial.h polynomial.cpp
	g++ -std=c++11 hw07.cpp polynomial.h polynomial.cpp -o test

run:
	g++ -std=c++11 hw07.cpp polynomial.h polynomial.cpp -o test    
	./test

clean: test
	rm test
