all: superamazingquickhash.h run.cpp
	g++ -std=c++11 run.cpp superamazingquickhash.h -o run

run: superamazingquickhash.h run.cpp
	g++ -std=c++11 run.cpp superamazingquickhash.h -o run
	./run

clean: run
	rm run	